name: 编译mipsel版iperf3

on:
  schedule:
    - cron: '0 3,20 * * *'
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      ver: ${{ steps.getversion.outputs.ver }}
      cver: ${{ steps.getversion.outputs.cver }}
    steps:
      -
        name: 检查更新
        id: getversion
        run: |
          ver=`curl https://api.github.com/repos/esnet/iperf/releases/latest | jq -r '.tag_name'`
          cver=`curl https://api.github.com/repos/lmq8267/iperf3/releases/latest | jq -r '.tag_name'`
          echo "ver=${ver}" >> $GITHUB_OUTPUT
          echo "cver=${cver}" >> $GITHUB_OUTPUT

  build:
    runs-on: ubuntu-latest
    needs: check
    if: ${{ needs.check.outputs.ver != needs.check.outputs.cver }}
    steps:
      -
        name: 检查代码仓库
        uses: actions/checkout@v3
      - name: Init submodules
        uses: snickerbockers/submodules-init@v4
      - name: 编译
        run: |
          mkdir -p ./musl_gcc 
          mkdir -p ./musl_gcc-arm64
          mkdir -p ./mipsel
          mkdir -p ./arm64
          wget -c https://musl.cc/mipsel-linux-musl-cross.tgz -P /opt/musl_gcc/
          tar zxf /opt/musl_gcc/mipsel-linux-musl-cross.tgz -C /opt/musl_gcc/
          sudo rm -rf /usr/bin/gcc
          sudo rm -rf /usr/bin/ld
          sudo rm -rf /usr/bin/ar
          sudo ln -sf /opt/musl_gcc/mipsel-linux-musl-cross/bin/mipsel-linux-musl-gcc /usr/bin/gcc
          sudo ln -sf /opt/musl_gcc/mipsel-linux-musl-cross/bin/mipsel-linux-musl-ld /usr/bin/ld
          sudo ln -sf /opt/musl_gcc/mipsel-linux-musl-cross/bin/mipsel-linux-musl-ar /usr/bin/ar
          git clone https://github.com/esnet/iperf -b ${{ needs.check.outputs.ver }} /opt/iperf
          git clone https://github.com/lmq8267/cloudflared.git /opt/st
          tar -xvf /opt/st/upx-3.95-amd64_linux.tar.xz -C /opt
          tar -xvf /opt/st/upx-4.1.0-amd64_linux.tar.xz -C /opt
          chmod 777 /opt/upx-3.95-amd64_linux/upx
          chmod 777 /opt/upx-4.1.0-amd64_linux/upx
          chmod 777 /opt/st/strip
          wget -c https://musl.cc/aarch64-linux-musl-cross.tgz -P /opt/musl_gcc-arm64/
          tar zxf /opt/musl_gcc-arm64/aarch64-linux-musl-cross.tgz -C /opt/musl_gcc-arm64/
          chmod 777 /opt/musl_gcc-arm64/aarch64-linux-musl-cross/bin/aarch64-linux-musl-strip
          cd /opt/iperf
          ./configure LDFLAGS=-static --host=mipsel-linux-musl --build=x86 --target=mipsel-linux --without-openssl --disable-shared --enable-static-bin CFLAGS=-static
          make
          sudo cp -rf /opt/iperf/src/iperf3 /opt/mipsel/iperf3_musl_mipsel
          /opt/st/strip /opt/mipsel/iperf3_musl_mipsel 
          cd /opt/mipsel
          /opt/upx-3.95-amd64_linux/upx --lzma --best iperf3_musl_mipsel
          cd /opt/iperf
          make clean
          export CC=/opt/musl_gcc-arm64/aarch64-linux-musl-cross/bin/aarch64-linux-musl-gcc
          export LD=/opt/musl_gcc-arm64/aarch64-linux-musl-cross/bin/aarch64-linux-musl-ld
          export AR=/opt/musl_gcc-arm64/aarch64-linux-musl-cross/bin/aarch64-linux-musl-ar
          ./configure LDFLAGS=-static --host=aarch64-linux-musl --build=x86 --target=aarch64-linux CC=/opt/musl_gcc-arm64/aarch64-linux-musl-cross/bin/aarch64-linux-musl-gcc --without-openssl --disable-shared --enable-static-bin CFLAGS=-static
          make
          sudo cp -rf /opt/iperf/src/iperf3 /opt/arm64/iperf3_musl_aarch64
          /opt/musl_gcc-arm64/aarch64-linux-musl-cross/bin/aarch64-linux-musl-strip /opt/arm64/iperf3_musl_aarch64
          cd /opt/arm64
          /opt/upx-4.1.0-amd64_linux/upx --lzma --best iperf3_musl_aarch64
          
      - 
        name: 发布
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.c8 }}
          tag_name: ${{ needs.check.outputs.ver }}
          files: |
              /opt/mipsel/iperf3_musl_mipsel
              /opt/arm64/iperf3_musl_aarch64 
      - 
       name: 删除工作流
       uses: GitRML/delete-workflow-runs@main
       with:
        token: ${{ secrets.c8 }}
        retain_days: 2
        keep_minimum_runs: 0
